// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;

import static edu.wpi.first.units.Units.RotationsPerSecond;
import static edu.wpi.first.units.Units.RotationsPerSecondPerSecond;
import static edu.wpi.first.units.Units.Second;
import static edu.wpi.first.units.Units.Volts;

import com.ctre.phoenix6.StatusCode;
import com.ctre.phoenix6.configs.MotionMagicConfigs;
import com.ctre.phoenix6.configs.MotorOutputConfigs;
import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.controls.MotionMagicVoltage;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.signals.NeutralModeValue;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.robot.Constants;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class climb extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private TalonFX raiser;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public double raiserUpperTarget;
    public double raiserLowerTarget;
    public boolean climbing;

    private final MotionMagicVoltage m_motionMagicReq = new MotionMagicVoltage(0).withSlot(0);
    TalonFXConfiguration climbConf = new TalonFXConfiguration();
    /**
    *
    */
    public climb() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        raiser = new TalonFX(14, "rio");
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        raiserUpperTarget = Constants.ClimbConstants.raiserUpperTarget;
        raiserLowerTarget = Constants.ClimbConstants.raiserLowerTarget;
        climbing = false;


        // Configs
        // CurrentLimitsConfigs climbCurrent = climbConf.CurrentLimits;
        // climbCurrent.StatorCurrentLimit = Constants.ClimbConstants.climbCurrentLimit;
        MotorOutputConfigs climbOutput = climbConf.MotorOutput;
        // climbOutput.Inverted = InvertedValue.CounterClockwise_Positive;
        climbOutput.NeutralMode = NeutralModeValue.Brake;
  
        climbConf.Slot0.kP = 0.4; // An error of 1 rotation results in 2.4 V output
        climbConf.Slot0.kI = 0.0075; // No output for integrated error
        climbConf.Slot0.kD = 0; // A velocity of 1 rps results in 0.1 V output
        climbConf.Slot0.kS = 0.17558;
        climbConf.Slot0.kV = 0.11202;
        climbConf.Slot0.kA = 0.0024753;

        // climbConf.Slot0.GravityType = GravityTypeValue.Arm_Cosine;

        // // Peak output of 8 V
        climbConf.Voltage.withPeakForwardVoltage(Volts.of(10)).withPeakReverseVoltage(Volts.of(-10));

        MotionMagicConfigs motionMagicOn = climbConf.MotionMagic;
        motionMagicOn.withMotionMagicCruiseVelocity(RotationsPerSecond.of(499))
                .withMotionMagicAcceleration(RotationsPerSecondPerSecond.of(100))
                .withMotionMagicJerk(RotationsPerSecondPerSecond.per(Second).of(0)); // 0 makes it fast
        
        /* Retry config apply up to 5 times, report if failure */
        StatusCode status = StatusCode.StatusCodeNotInitialized;
        for (int i = 0; i < 5; ++i) {
            status = raiser.getConfigurator().apply(climbConf);
            if (status.isOK())
                break;
        }
        if (!status.isOK()) {
            System.out.println("Could not apply configs, error code: " + status.toString());
        }
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run
        SmartDashboard.putNumber("Position", raiser.getPosition().getValueAsDouble());
        SmartDashboard.putNumber("Velocity", raiser.getVelocity().getValueAsDouble());
        SmartDashboard.putBoolean("Climbing", climbing);
    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }
    public void stopClimbing() {
        raiser.set(0);
    }
    public void setUpperPosition(){
        raiser.setControl(m_motionMagicReq.withPosition(raiserUpperTarget));
        //climbing = true;
    }
    public void setLowerPosition(){
        raiser.setControl(m_motionMagicReq.withPosition(raiserLowerTarget));
        //climbing = false;
    }
    public boolean isRaised(){
        return Math.abs(raiser.getPosition().getValueAsDouble()  - raiserUpperTarget) < .3;
    }
    public boolean isLowered(){
        return Math.abs(raiser.getPosition().getValueAsDouble()  - raiserLowerTarget) < .3;
    }
    public boolean isClimbing () {
        return climbing;
    }
    public boolean toggleClimbing() {
        return climbing = !climbing;
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    

}

